// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzfctxwjngtjzhswpojx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6ZmN0eHdqbmd0anpoc3dwb2p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NTc4NDEsImV4cCI6MjA3MzIzMzg0MX0.b1icXIY_CJSwIzZNojgtiTL-4xnPp3-SJxRSPcytMcE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});